### PR TITLE
discuss: change CLINVAR id from RCV to Variant ID

### PR DESCRIPTION
**Pull request by colleenXu**

### CODE REVIEW

**Comment by newgene** [comment]
@colleenXu what's the justification to switch to using ClinVar variant_id instead of RCV id? Is that the primary ID for Clinvar in Biolink model? Just need a description to document why we made this change.

I also suggest to remove `dbnsfp.clinvar.clinvar_id`, `clinvar` field should be the canonical source for ClinVar.

**Comment by colleenXu** [comment]
@newgene It's not clear to me which ID the biolink-model is referring to with the CLINVAR prefix. See the id_prefixes [here](https://github.com/biolink/biolink-model/blob/615629a4e3ad198b68c3ef08c4e8935816c7deb3/biolink-model.yaml#L8355) (wait...there's CLINVAR and ClinVarVariant? What are these?).

Based on my reading on [Clinvar identifiers](https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/) and this [FAQ](https://www.ncbi.nlm.nih.gov/clinvar/docs/faq/#var_rcv) on RCV, it seemed that RCV were more like an association's ID (phenotype/disease + variant). 

So I thought maybe a different ID from clinvar refers to the SequenceVariant itself and should be used...

According to the linked Clinvar doc on [identifiers]((https://www.ncbi.nlm.nih.gov/clinvar/docs/identifiers/)), the closest to a "unique variant ID" is maybe a "VariationID" or "AlleleID"?

**Comment by newgene** [comment]
OK, if this does not link to a known issue or expected use case, I would hold off this one. 

We are making changes to ClinVar source at MyVariant.info now: https://github.com/biothings/myvariant.info/issues/127. Will reevaluate this after this myvariant issue is closed.

**Comment by colleenXu** [comment]
Based on the conversation in NCATSTranslator Slack, the CLINVAR ID prefix for SequenceVariant refers to the "Variation ID" in Clinvar. 

My recommendation is to go forward with this PR, once I add a commit to remove the dbnsfp field mapping...

I've confirmed that the clinvar.variant_id field in MyVariant corresponds to the Clinvar Variation ID. For example, see how the [clinvar.variant_id:596318](https://myvariant.info/v1/query?q=clinvar.variant_id:596318&fields=clinvar) corresponds to the record [here](http://reg.clinicalgenome.org/redmine/projects/registry/genboree_registry/by_caid?caid=CA4925810) that states that the Clinvar Variation ID is also 596318

**Pull request merged**
