### PR TITLE
add ClinicalFinding semantic type

### PR DESCRIPTION
**Pull request by colleenXu**
Not critical, but this would support ID resolution and handling this semantic type for Multiomics Provider Wellness API. Currently we don't have any ID resolution (which leads to bugs in handling these IDs / semantic type).

### CODE REVIEW

**Comment by newgene** [comment]
Ideally, add the relevant tests @colleenXu

**Comment by colleenXu** [comment]
I'll note in my to-dos that tests would ideally be added for clinical finding, especially if we will work more with this semantic type going forward

**Comment by colleenXu** [comment]
Note that we have changed to using refactored ID resolver with SRI-based service (dev)...

It's not clear if code like this is used anymore, or what kind of tests need to be done (discussions in https://github.com/biothings/BioThings_Explorer_TRAPI/issues/283 and issues that I will create later)

**Comment by ericz1803** [comment]
Looks like the code you changed is part of the old resolver. All of the code for the new SRI-based resolver is in `sri.ts` so if it isn't able to resolve it it is probably SRI not handling it

**Pull request merged**
